/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.ManipularImagem;
import dao.PessoasDAO;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import negocios.pessoas;

/**
 *
 * @author patri
 */
public class TelaEditarMinhaConta extends javax.swing.JInternalFrame {
    private boolean a = false;
    private int id = 0;
    BufferedImage imagem;
    private pessoas pessoa = new pessoas ();
    
    /**
     * Creates new form TelaEditarMinhaConta
     */
    public TelaEditarMinhaConta(pessoas p) {
        initComponents();
        id = p.getId_pessoas();
        this.popularMeusDados(p);
        pessoa = p;
    }
    public void popularMeusDados (pessoas o){
        this.CampoNome.setText(o.getNome());
        this.CampoNomeDeUsuario.setText(o.getNomeUsuario());
        this.CampoRua.setText(o.getRua());
        this.CampoEmail.setText(o.getEmail());
        this.CampoNumeroDaCasa.setText(""+o.getNumeroCasa());
        this.CampoBairro.setText(o.getBairro());
        PessoasDAO peDAO = new PessoasDAO ();
        this.CampoCidade.setText(peDAO.conslutarNomeCidade(o));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoNomeDeUsuario = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoRua = new javax.swing.JTextField();
        CampoNumeroDaCasa = new javax.swing.JTextField();
        CampoBairro = new javax.swing.JTextField();
        CampoCidade = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JTextField();
        BtnAlterarEndereco = new javax.swing.JButton();
        BtnAlterarNomeUsuario = new javax.swing.JButton();
        BtnAlterarSenha = new javax.swing.JButton();

        setClosable(true);
        setTitle("SiGames: Editar Minha Conta");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nome de usuário:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Rua:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Número da casa:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Bairro:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Cidade:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Nova senha:");

        CampoNome.setEditable(false);
        CampoNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CampoNomeDeUsuario.setEditable(false);
        CampoNomeDeUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoNomeDeUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CampoEmail.setEditable(false);
        CampoEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CampoRua.setEditable(false);
        CampoRua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoRua.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CampoNumeroDaCasa.setEditable(false);
        CampoNumeroDaCasa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoNumeroDaCasa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CampoBairro.setEditable(false);
        CampoBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoBairro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CampoCidade.setEditable(false);
        CampoCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoCidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CampoSenha.setEditable(false);
        CampoSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        BtnAlterarEndereco.setBackground(new java.awt.Color(64, 77, 137));
        BtnAlterarEndereco.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        BtnAlterarEndereco.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlterarEndereco.setText("Alterar Endereço");
        BtnAlterarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarEnderecoActionPerformed(evt);
            }
        });

        BtnAlterarNomeUsuario.setBackground(new java.awt.Color(64, 77, 137));
        BtnAlterarNomeUsuario.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        BtnAlterarNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlterarNomeUsuario.setText("Alterar Nome de Usuário");
        BtnAlterarNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarNomeUsuarioActionPerformed(evt);
            }
        });

        BtnAlterarSenha.setBackground(new java.awt.Color(64, 77, 137));
        BtnAlterarSenha.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        BtnAlterarSenha.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlterarSenha.setText("Alterar Senha");
        BtnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAlterarEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAlterarNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAlterarSenha)
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(CampoNomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(CampoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(CampoNumeroDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(CampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(CampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(CampoNomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CampoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CampoNumeroDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAlterarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAlterarNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        setBounds(400, 50, 538, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAlterarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarEnderecoActionPerformed
        String ver = this.CampoNome.getText();
        ver = ver.replace(" ", "");
        boolean ver1 = false;
        if (a == false){
            this.CampoRua.setEditable(true);
            this.CampoNumeroDaCasa.setEditable(true);
            this.CampoBairro.setEditable(true);
            this.CampoCidade.setEditable(true);
            this.BtnAlterarEndereco.setText("Salvar");
            a = true;
        }else {
            if (ver1 == false){
                ver = this.CampoRua.getText();
                ver = ver.replace(" ", "");
                if (ver.isEmpty()){
                    ver1 = true;
                }
                if (ver1 == false){
                    ver = this.CampoNumeroDaCasa.getText();
                    ver = ver.replace(" ", "");
                    if (ver.isEmpty()){
                        ver1 = true;
                    }
                    if (ver1 == false){
                        ver = this.CampoBairro.getText();
                        ver = ver.replace(" ", "");
                        if (ver.isEmpty()){
                            ver1 = true;
                        }
                        if (ver1 == false){
                            ver = this.CampoCidade.getText();
                            ver = ver.replace(" ", "");
                            if (ver.isEmpty()){
                                ver1 = true;
                            }
                            if (ver1 == false ){
                                try {
                                    PessoasDAO peDAO = new PessoasDAO ();
                                    String var = (""+id);

                                    peDAO.atualizarEndereco(var, this.CampoRua.getText(), this.CampoNumeroDaCasa.getText(), this.CampoBairro.getText(), this.CampoCidade.getText());

                                    this.BtnAlterarEndereco.setText("Alterar Endereço");
                                    this.CampoRua.setEditable(false);
                                    this.CampoNumeroDaCasa.setEditable(false);
                                    this.CampoBairro.setEditable(false);
                                    this.CampoCidade.setEditable(false);
                                    a = false;
                                    JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso!");
                                } catch (Exception e){
                                    System.out.println(""+ e);
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Preencha o nome da cidade!");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Preencha o nome do bairro!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha o número da casa!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Preencha o nome da rua!");
                }
            } else {

            }
        }
    }//GEN-LAST:event_BtnAlterarEnderecoActionPerformed

    private void BtnAlterarNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarNomeUsuarioActionPerformed
        String ver = this.CampoNomeDeUsuario.getText();
        ver = ver.replace(" ", "");
        boolean ver1 = false;
        if (a == false){
            this.CampoNomeDeUsuario.setEditable(true);
            this.BtnAlterarNomeUsuario.setText("Salvar");
            a = true;
        } else {
            if (ver1 == false){
                ver = this.CampoNomeDeUsuario.getText();
                ver = ver.replace(" ", "");
                if (ver.isEmpty()){
                    ver1 = true;
                }if (ver1 == false){
                    try {
                        PessoasDAO peDAO = new PessoasDAO ();
                        String var = (""+id);
                        peDAO.atualizarNomeUser(var, this.CampoNomeDeUsuario.getText());

                        this.CampoNomeDeUsuario.setEditable(false);
                        this.BtnAlterarNomeUsuario.setText("Alterar Nome de Usuário");
                        a = false;
                        JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso!");
                    } catch (Exception e){
                        System.out.println(""+ e);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Preencha o seu novo nome de usuário!");
                }
            }
        }
    }//GEN-LAST:event_BtnAlterarNomeUsuarioActionPerformed

    private void BtnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarSenhaActionPerformed
        String ver = this.CampoSenha.getText();
        ver = ver.replace(" ", "");
        boolean ver1 = false;
        if (a == false){
            this.CampoSenha.setEditable(true);
            this.BtnAlterarSenha.setText("Salvar");
            a = true;
        } else {
            if (ver1 == false){
                ver = this.CampoSenha.getText();
                ver = ver.replace(" ", "");
                if (ver.isEmpty()){
                    ver1 = true;
                }if (ver1 == false){
                    try {
                        PessoasDAO peDAO = new PessoasDAO ();
                        String var = (""+id);
                        peDAO.atualizarSenha(var, this.CampoSenha.getText());

                        this.CampoSenha.setEditable(false);
                        this.CampoSenha.setText("");
                        this.BtnAlterarSenha.setText("Alterar Senha");
                        a = false;
                        JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso!");
                    } catch (Exception e){
                        System.out.println(""+ e);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Preencha a sua nova senha!");
                }
            }
        }
    }//GEN-LAST:event_BtnAlterarSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterarEndereco;
    private javax.swing.JButton BtnAlterarNomeUsuario;
    private javax.swing.JButton BtnAlterarSenha;
    private javax.swing.JTextField CampoBairro;
    private javax.swing.JTextField CampoCidade;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNomeDeUsuario;
    private javax.swing.JTextField CampoNumeroDaCasa;
    private javax.swing.JTextField CampoRua;
    private javax.swing.JTextField CampoSenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
