/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.ComboItem;
import apoio.CombosDAO;
import negocios.pedidos;
import java.util.Date;
import dao.PedidosDAO;
import dao.PedidosVideoDAO;

/**
 *
 * @author patri
 */
public class TelaConsultaVideo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultaVideo
     */
    public TelaConsultaVideo() {
        initComponents();
        new CombosDAO ().popularCombo("forma_de_pagamento", "id_forma_de_pagamento", "nome", jComboBoxPagamento, "");
        new PedidosDAO().popularTabela(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnPesquisar = new javax.swing.JButton();
        campoNomeCliente = new javax.swing.JTextField();
        campoNomeGane = new javax.swing.JTextField();
        Data_fim = new com.toedter.calendar.JDateChooser();
        Data_ini = new com.toedter.calendar.JDateChooser();
        jComboBoxPagamento = new javax.swing.JComboBox<>();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        campoID_Pedido = new javax.swing.JTextField();

        setClosable(true);
        setTitle("SiGames: Consulta Vídeo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nome do Cliente:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome do Game:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Data Início:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Data Fim:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("ID do Pedido:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Situação:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Forma de Pagamento:");

        BtnPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        jComboBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSituacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "A", "C" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoNomeGane, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Data_fim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(Data_ini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoID_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnPesquisar))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeGane, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoID_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Data_ini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Data_fim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        setBounds(260, 15, 833, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        pedidos p = new pedidos ();
        PedidosDAO pDAO = new PedidosDAO ();
        PedidosVideoDAO pvDAO = new PedidosVideoDAO ();
        
        boolean nome_pessoa = false ;
        boolean nome_jogo = false ; 
        boolean id_pedido = false ;
        boolean data_ini = false ;
        boolean data_fim = false ;
        boolean situacao = false ;
        boolean pagamento = false ;
        String campoNomePessoa = null;
        String campoID = null;
        String campoNomeJogo = null;
        String campoPagamento = null;
        String campoSituacao = null;
        Date dataIni = null;
        Date dataFim = null;
        
        campoNomePessoa = this.campoNomeCliente.getText();
        campoID = this.campoID_Pedido.getText();
        campoNomeJogo = this.campoNomeGane.getText();
        campoPagamento = (""+jComboBoxPagamento.getSelectedItem());
        campoSituacao = (""+jComboBoxSituacao.getSelectedItem());
        dataIni = Data_ini.getDate();
        dataFim = Data_fim.getDate();
        
        if(! campoNomePessoa.isEmpty()){
            nome_pessoa = true;
            p.setNomePessoa(campoNomePessoa);
        }
        if(! campoID.isEmpty()){
            id_pedido = true;
            p.setId_pedido(Integer.parseInt(campoID));
        }
        if(! campoNomeJogo.isEmpty()){
            nome_jogo = true;
            p.setNomeJogo(campoNomeJogo);
        }
        if (! campoPagamento.equals("Selecione")){
            pagamento = true;
            ComboItem c = (ComboItem) this.jComboBoxPagamento.getSelectedItem();
            p.setId_forma_pagamento(c.getCodigo());
        }
        if (! campoSituacao.equals("Selecione")){
            situacao = true;
            p.setSituacao(campoSituacao);
        }
        if (dataIni != null){
            data_ini = true;
            p.setDataIni(dataIni);
        }
        if (dataFim != null){
            data_fim = true;
            p.setDataFim(dataFim);
        }
        
        if(nome_pessoa == false){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == false){
                        if (data_fim == false){
                            if(situacao == false){
                                if (pagamento == false){
                                    pDAO.popularTabela(jTable1);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == false){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == true){
                        if (data_fim == true){
                            if(situacao == false){
                                if (pagamento == false){
                                    pvDAO.popular_tabela_passandoData(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == true){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == false){
                        if (data_fim == false){
                            if(situacao == false){
                                if (pagamento == false){
                                    pvDAO.popular_tabela_passandoNomePessoa(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == false){
            if(nome_jogo == true){
                if(id_pedido == false){
                    if(data_ini == false){
                        if (data_fim == false){
                            if(situacao == false){
                                if (pagamento == false){
                                    pvDAO.popular_tabela_passandoNomeGame(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == false){
            if(nome_jogo == false){
                if(id_pedido == true){
                    if(data_ini == false){
                        if (data_fim == false){
                            if(situacao == false){
                                if (pagamento == false){
                                    pvDAO.popular_tabela_passandoID_Pedido(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == false){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == false){
                        if (data_fim == false){
                            if(situacao == true){
                                if (pagamento == false){
                                    pvDAO.popular_tabela_passandoSituacao(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == false){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == false){
                        if (data_fim == false){
                            if(situacao == false){
                                if (pagamento == true){
                                    pvDAO.popular_tabela_passandoFormaDePagamento(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == false){
            if(nome_jogo == true){
                if(id_pedido == false){
                    if(data_ini == true){
                        if (data_fim == true){
                            if(situacao == false){
                                if (pagamento == false){
                                    pvDAO.popular_tabela_passandoNomeJogo_E_Data(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == false){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == true){
                        if (data_fim == true){
                            if(situacao == false){
                                if (pagamento == true){
                                    pvDAO.popular_tabela_passandoFormaDePagamento_E_Data(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == true){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == true){
                        if (data_fim == true){
                            if(situacao == false){
                                if (pagamento == false){
                                    pvDAO.popular_tabela_passandoNomePessoa_E_Data(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == true){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == true){
                        if (data_fim == true){
                            if(situacao == false){
                                if (pagamento == true){
                                    pvDAO.popular_tabela_passandoNomePessoa_Data_FormaPagamento(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(nome_pessoa == true){
            if(nome_jogo == false){
                if(id_pedido == false){
                    if(data_ini == false){
                        if (data_fim == false){
                            if(situacao == false){
                                if (pagamento == true){
                                    pvDAO.popular_tabela_passandoNomePessoa_E_FormaPagamento(jTable1, p);
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_BtnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPesquisar;
    private com.toedter.calendar.JDateChooser Data_fim;
    private com.toedter.calendar.JDateChooser Data_ini;
    private javax.swing.JTextField campoID_Pedido;
    private javax.swing.JTextField campoNomeCliente;
    private javax.swing.JTextField campoNomeGane;
    private javax.swing.JComboBox<String> jComboBoxPagamento;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
