/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.CombosDAO;
import dao.GeneroDAO;
import javax.swing.JOptionPane;
import negocios.genero;

/**
 *
 * @author patri
 */
public class TelaCadastrarCategorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastrarCategorias
     */
    public TelaCadastrarCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CampoNomeCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDescCateg = new javax.swing.JTextPane();
        BtnCadastrarCategorias = new javax.swing.JButton();

        setClosable(true);
        setTitle("SiGames: Cadastrar Categorias");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Adicionar Nome da Categoria:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CampoNomeCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoNomeCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CampoNomeCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Descrição da Categoria:");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextPaneDescCateg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextPaneDescCateg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextPaneDescCateg);

        BtnCadastrarCategorias.setBackground(new java.awt.Color(64, 77, 137));
        BtnCadastrarCategorias.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnCadastrarCategorias.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrarCategorias.setText("Cadastrar");
        BtnCadastrarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarCategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnCadastrarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                        .addComponent(CampoNomeCategoria)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(BtnCadastrarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        setBounds(350, 50, 600, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeCategoriaActionPerformed

    private void BtnCadastrarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarCategoriasActionPerformed
        genero genero = new genero ();
        String ver ;
        boolean ver1 = false;

        genero.setNome(this.CampoNomeCategoria.getText());
        genero.setDescricao(this.jTextPaneDescCateg.getText());

        GeneroDAO genDAO = new GeneroDAO ();

        ver = this.CampoNomeCategoria.getText();
        ver = ver.replace(" ", "");
        if (ver.isEmpty()){
            ver1 = true;
        }
        if (ver1 == false){
            ver = this.jTextPaneDescCateg.getText();
            ver = ver.replace(" ", "");
            if (ver.isEmpty()){
                ver1 = true;
            }
            if (ver1 == false){
                if (genDAO.salvar(genero)){
                    JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");
                    this.CampoNomeCategoria.setText(" ");
                    this.jTextPaneDescCateg.setText(" ");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Problemas ao salvar registro!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Preencha a descrição da categoria!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha o nome da categoria!");
        }

    }//GEN-LAST:event_BtnCadastrarCategoriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrarCategorias;
    private javax.swing.JTextField CampoNomeCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneDescCateg;
    // End of variables declaration//GEN-END:variables
}
