/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import apoio.conexaoBD;
import negocios.genero;
import dao.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import negocios.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author patri
 */
public class TelaAdmin extends javax.swing.JFrame {
    private int set = 0;
    private int set2 = 0;

    /**
     * Creates new form TelaPrincipal1
     */
    public TelaAdmin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setResizable(true);
        this.setTitle("SiGames");
        new CidadesDAO ().popularTabela(this.jTableConsultar1, "");
        this.jButtonAlterrarConsulta1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel41 = new javax.swing.JLabel();
        jComboBoxConsultar1 = new javax.swing.JComboBox<>();
        CampoBuscaCidades1 = new javax.swing.JTextField();
        BtnPesquisarConsulta1 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jButtonAlterrarConsulta1 = new javax.swing.JButton();
        jButtonEditarConsulta1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableConsultar1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 77, 137));
        jPanel1.setForeground(new java.awt.Color(64, 77, 137));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 50));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SiGames");

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/certas/016-logout.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)))
                .addGap(19, 19, 19))
        );

        jLabel41.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel41.setText("Consultar:");

        jComboBoxConsultar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxConsultar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cidades", "Clientes", "Estoque", "Jogos", "Pedidos" }));
        jComboBoxConsultar1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxConsultar1ItemStateChanged(evt);
            }
        });
        jComboBoxConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxConsultar1MouseClicked(evt);
            }
        });
        jComboBoxConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsultar1ActionPerformed(evt);
            }
        });

        BtnPesquisarConsulta1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnPesquisarConsulta1.setText("Pesquisar");
        BtnPesquisarConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarConsulta1ActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel42.setText("Legendas do campo situação:");

        jLabel46.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(64, 77, 137));
        jLabel46.setText("A");

        jLabel49.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(64, 77, 137));
        jLabel49.setText("I");

        jLabel45.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(64, 77, 137));
        jLabel45.setText("D");

        jLabel51.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(64, 77, 137));
        jLabel51.setText("I");

        jLabel43.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel43.setText("Clientes:");

        jLabel47.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel47.setText("=  Ativo");

        jLabel50.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel50.setText("=  Inativo");

        jLabel44.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel44.setText("Jogos:");

        jLabel48.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel48.setText("=  Disponível");

        jLabel52.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel52.setText("=  Indisponível");

        jButtonAlterrarConsulta1.setBackground(new java.awt.Color(64, 77, 137));
        jButtonAlterrarConsulta1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAlterrarConsulta1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlterrarConsulta1.setText("Alterar");
        jButtonAlterrarConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterrarConsulta1ActionPerformed(evt);
            }
        });

        jButtonEditarConsulta1.setBackground(new java.awt.Color(64, 77, 137));
        jButtonEditarConsulta1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonEditarConsulta1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarConsulta1.setText("Editar");
        jButtonEditarConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarConsulta1ActionPerformed(evt);
            }
        });

        jTableConsultar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultar1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableConsultar1);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Pedidos:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 77, 137));
        jLabel5.setText("A");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("=  Aprovado");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 77, 137));
        jLabel7.setText("C");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("=  Concluído");

        jDesktopPane2.setLayer(jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jComboBoxConsultar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(CampoBuscaCidades1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(BtnPesquisarConsulta1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel46, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel49, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel45, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel51, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel43, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel47, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel50, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel48, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel52, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButtonAlterrarConsulta1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButtonEditarConsulta1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane2Layout.createSequentialGroup()
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                            .addComponent(jLabel44)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel45)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel48)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel51)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel52))
                                        .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAlterrarConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                    .addComponent(jLabel43)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel46)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel47)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel49)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel50)))
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEditarConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPane2Layout.createSequentialGroup()
                            .addComponent(jLabel41)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CampoBuscaCidades1)
                            .addGap(18, 18, 18)
                            .addComponent(BtnPesquisarConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel42))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoBuscaCidades1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BtnPesquisarConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditarConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAlterrarConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel48)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addGap(24, 24, 24))
        );

        jMenu3.setText("Atualizar Estoque   |");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Cadastrar   |");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Categorias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cidades");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Estados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Jogos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Consulta  |");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Relatórios");

        jMenuItem8.setText("Listagem - Estoque");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Listagem - Jogos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem7.setText("Relatório - Clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem10.setText("Relatório - Pedidos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1371, Short.MAX_VALUE)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void addEstoque (String a){
        int j = 0;
        GamesDAO game = new GamesDAO ();
        EstoqueDAO estoqueDao = new EstoqueDAO();
        estoque est = new estoque();
        
        j = game.consultar_id(a);
        est.setId_jogos(j);
        estoqueDao.salvar(est);
    }
    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCadastrarCategorias tela = new TelaCadastrarCategorias();
        jDesktopPane2.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String a = "Cadastrar";
        int x = 0;
        String n = "";
        int w = 0;
        int j = 0;
        TelaCadastrarCidades tela = new TelaCadastrarCidades(x , n , w , a, j);
        jDesktopPane2.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        games g = new games ();
        g.setUtil("Cadastrar");
        g.setNome("sda");
        TelaCadastrarGames tela = new TelaCadastrarGames(g);
        jDesktopPane2.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
 
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        TelaAtualizarEstoque tela = new TelaAtualizarEstoque();
        jDesktopPane2.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jComboBoxConsultar1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxConsultar1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConsultar1ItemStateChanged

    private void jComboBoxConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxConsultar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConsultar1MouseClicked

    private void jComboBoxConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsultar1ActionPerformed
        if (this.jComboBoxConsultar1.getSelectedItem().equals("Cidades") ){
            new CidadesDAO ().popularTabela(this.jTableConsultar1, "");
            this.jButtonAlterrarConsulta1.setVisible(false);
            this.jButtonEditarConsulta1.setVisible(true);
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Clientes") ){
            new PessoasDAO ().popularTabela(this.jTableConsultar1, "");
            this.jButtonAlterrarConsulta1.setVisible(true);
            this.jButtonEditarConsulta1.setVisible(true);
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Estoque") ){
            new EstoqueDAO ().popularTabela(this.jTableConsultar1);
            this.jButtonAlterrarConsulta1.setVisible(false);
            this.jButtonEditarConsulta1.setVisible(false);
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Jogos") ){
            new GamesDAO ().popularTabela(this.jTableConsultar1, "");
            this.jButtonAlterrarConsulta1.setVisible(true);
            this.jButtonEditarConsulta1.setVisible(true);
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Pedidos") ){
            new PedidosDAO ().popularTabela(this.jTableConsultar1);
            this.jButtonAlterrarConsulta1.setVisible(true);
            this.jButtonEditarConsulta1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxConsultar1ActionPerformed

    private void BtnPesquisarConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarConsulta1ActionPerformed
        if (! this.CampoBuscaCidades1.getText().isEmpty()){
            if (this.jComboBoxConsultar1.getSelectedItem().equals("Cidades") ){
                new CidadesDAO ().popularTabela(this.jTableConsultar1, this.CampoBuscaCidades1.getText());
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Clientes") ){
                new PessoasDAO ().popularTabela(this.jTableConsultar1, this.CampoBuscaCidades1.getText());
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Estoque") ){
                new EstoqueDAO ().popularTabela_por_pesquisa(this.jTableConsultar1, this.CampoBuscaCidades1.getText());
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Jogos") ){
                new GamesDAO ().popularTabela(this.jTableConsultar1, this.CampoBuscaCidades1.getText());
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Pedidos") ){
                int i = Integer.parseInt(this.CampoBuscaCidades1.getText());
                new PedidosDAO ().popular_tabela_por_pesquisa(this.jTableConsultar1, i );
            }
        } else {
            if (this.jComboBoxConsultar1.getSelectedItem().equals("Cidades") ){
                new CidadesDAO ().popularTabela(this.jTableConsultar1, this.CampoBuscaCidades1.getText());
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Clientes") ){
                new PessoasDAO ().popularTabela(this.jTableConsultar1, this.CampoBuscaCidades1.getText());
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Estoque") ){
                new EstoqueDAO ().popularTabela(this.jTableConsultar1);
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Jogos") ){
                new GamesDAO ().popularTabela(this.jTableConsultar1, this.CampoBuscaCidades1.getText());
            }
            else if (this.jComboBoxConsultar1.getSelectedItem().equals("Pedidos") ){
                new PedidosDAO ().popularTabela(this.jTableConsultar1);
            }
        }
    }//GEN-LAST:event_BtnPesquisarConsulta1ActionPerformed

    private void jButtonAlterrarConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterrarConsulta1ActionPerformed
        if (this.jComboBoxConsultar1.getSelectedItem().equals("Clientes") ){
            String id;
            int coluna = 0;
            int codigo;
            String consulta;
            int coluna2 = 9;

            id = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna).toString();
            codigo = Integer.parseInt(id);
            consulta =jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna2).toString();

            if (consulta.equals("A")){
                new PessoasDAO().excluir(codigo);
            }
            if (consulta.equals("I")) {
                new PessoasDAO().ativar(codigo);
            }

            new PessoasDAO ().popularTabela(this.jTableConsultar1, "");
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Jogos") ){
            String id;
            int coluna = 0;
            int codigo;
            String consulta;
            int coluna2 = 4;

            id = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna).toString();
            codigo = Integer.parseInt(id);
            consulta = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna2).toString();

            if (consulta.equals("D")){
                new GamesDAO().excluir(codigo);
            }
            if (consulta.equals("I")) {
                new GamesDAO ().ativar(codigo);
            }

            new GamesDAO ().popularTabela(jTableConsultar1, "");
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Pedidos") ){
            String id;
            int coluna = 0;
            int codigo;
            String consulta;
            int coluna2 = 5;

            id = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna).toString();
            codigo = Integer.parseInt(id);
            consulta = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna2).toString();

            if (consulta.equals("A")){
                new PedidosDAO().excluir(codigo);
            }
            if (consulta.equals("C")) {
                new PedidosDAO ().ativar(codigo);
            }
            new PedidosDAO ().popularTabela(this.jTableConsultar1);
        }
    }//GEN-LAST:event_jButtonAlterrarConsulta1ActionPerformed

    private void jButtonEditarConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarConsulta1ActionPerformed
        if (this.jComboBoxConsultar1.getSelectedItem().equals("Cidades") ){
            String id;
            int coluna = 0;
            int codigo;
            String nome;
            int coluna1 = 1;
            String cep;
            int coluna2 = 2;
            int cep2;
            int coluna3 = 3;
            String estado;
            int estado1;

            id = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna).toString();
            codigo = Integer.parseInt(id);
            nome = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna1).toString();
            cep = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna2).toString();
            cep2 = Integer.parseInt(cep);
            estado = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna3).toString();
            EstadoDAO est = new EstadoDAO ();
            estado1 = est.consultar_id(estado);
            set = codigo;

            String b = "Atualizar";
            TelaCadastrarCidades tela = new TelaCadastrarCidades(codigo, nome, cep2, b, estado1);
            jDesktopPane2.add(tela);
            tela.setVisible(true);
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Clientes") ){
            pessoas p = new pessoas ();
            String id; String nome; String email; String user; String rua; String numero_casa; String bairro; String cidade;
            
            id = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 0).toString();
            p.setId_pessoas(Integer.parseInt(id));
            nome = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 1).toString();
            p.setNome(nome);
            email = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 3).toString();
            p.setEmail(email);
            user = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 4).toString();
            p.setNomeUsuario(user);
            rua = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 6).toString();
            p.setRua(rua);
            numero_casa = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 7).toString();
            p.setNumeroCasa(Integer.parseInt(numero_casa));
            bairro = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 8).toString();
            p.setBairro(bairro);
            cidade = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), 10).toString();
            p.setId_cidade(new CidadesDAO().consultar_id(cidade));
            
            TelaEditarMinhaConta tela = new TelaEditarMinhaConta(p);
            jDesktopPane2.add(tela);
            tela.setVisible(true);
        }
        else if (this.jComboBoxConsultar1.getSelectedItem().equals("Jogos") ){
            String id; int coluna = 0; int codigo;
            String nome; int coluna1 = 1;
            String descricao; int coluna2 = 2;
            String valor; int coluna3 = 3;
            String genero; int genero1; int coluna5 = 5;

            id = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna).toString();
            codigo = Integer.parseInt(id);
            nome = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna1).toString();
            descricao = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna2).toString();
            valor = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna3).toString();
            genero = jTableConsultar1.getValueAt(jTableConsultar1.getSelectedRow(), coluna5).toString();
            GeneroDAO gen = new GeneroDAO ();
            genero1= gen.consultar_id(genero);
            games game = new games ();

            game.setUtil("Atualizar");
            game.setId_game(codigo);
            game.setNome(nome);
            game.setValor(valor);
            game.setId_genero(genero1);
            game.setDescricao(descricao);
            TelaCadastrarGames tela = new TelaCadastrarGames(game);
            jDesktopPane2.add(tela);
            tela.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditarConsulta1ActionPerformed

    private void jTableConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableConsultar1MouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/ReportsEstoque.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatoio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, conexaoBD.getInstance().getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
            /*JasperViewer.viewReport(impressao);*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        /*try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/ReportsClientes.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatoio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, conexaoBD.getInstance().getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
            /*JasperViewer.viewReport(impressao);*/
        /*} catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
        }*/
        DlgRelatoriosCliente dlg = new DlgRelatoriosCliente(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/ReportsGames1.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatoio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, conexaoBD.getInstance().getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
            /*JasperViewer.viewReport(impressao);*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaCadastrarEstado tela = new TelaCadastrarEstado();
        jDesktopPane2.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        DlgRelatoriosPedidos dlg = new DlgRelatoriosPedidos(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        TelaConsultaVideo tela = new TelaConsultaVideo();
        jDesktopPane2.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPesquisarConsulta1;
    private javax.swing.JTextField CampoBuscaCidades1;
    private javax.swing.JButton jButtonAlterrarConsulta1;
    private javax.swing.JButton jButtonEditarConsulta1;
    private javax.swing.JComboBox<String> jComboBoxConsultar1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTableConsultar1;
    // End of variables declaration//GEN-END:variables
}
