/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import apoio.ManipularImagem;
import negocios.games;
import dao.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.Buffer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import negocios.estoque;

/**
 *
 * @author patri
 */
public class TelaCadastrarGames extends javax.swing.JInternalFrame {
    BufferedImage imagem;
    private int id = 0;
    private String nome = "vazio";
    private String valor = "vazio";
    private int categoria = 0;
    private String descricao = "vazio";
    private String genero = "vazio";
    private String CadAtu = "vazio";
    
    /**
     * Creates new form TelaCadastrarGames
     */
    public TelaCadastrarGames(games g) {       
        initComponents();
        new Formatacao ().formatarNumero(CampoPrecoJogo);
        
        new CombosDAO ().popularCombo("genero", "id_genero", "nome", jComboCadJogo, "");
        jButtonCadJogos.setText(""+g.getUtil());
        CadAtu = g.getUtil();
        if (! g.getUtil().equals("Cadastrar")){
            int u;
            id = g.getId_game();
            nome = g.getNome();
            valor = g.getValor();
            categoria = g.getId_genero();
            descricao = g.getDescricao(); 
            GeneroDAO gen = new GeneroDAO ();
            genero = gen.consultar_nome(categoria);
            CampoNomeJogo.setText(nome);
            CampoPrecoJogo.setText(valor);
            jTextPaneDescJogo.setText(descricao);
            u = busca(genero);
            jComboCadJogo.setSelectedIndex(u);
        }
    }
    public static void addEstoque (String a){
        int j = 0;
        GamesDAO game = new GamesDAO ();
        EstoqueDAO estoqueDao = new EstoqueDAO();
        estoque est = new estoque();
        
        j = game.consultar_id(a);
        est.setId_jogos(j);
        estoqueDao.salvar(est);
    }
    
    public int busca (String nome){
        int a = 1;
        boolean d = false;
        while (d != true){
            jComboCadJogo.setSelectedIndex(a);
            String s = jComboCadJogo.getSelectedItem().toString();
            if (s.equals(nome)){
                d = true;
            } else {
               a++; 
            }
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        CampoNomeJogo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CampoPrecoJogo = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboCadJogo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPaneDescJogo = new javax.swing.JTextPane();
        jButtonCadJogos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();

        setClosable(true);
        setTitle("SiGames: Cadastrar Games");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Nome do Jogo:");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CampoNomeJogo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CampoNomeJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CampoNomeJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeJogoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Imagem Capa:");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Preço em R$ do jogo:");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CampoPrecoJogo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoPrecoJogo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Nome da categoria:");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboCadJogo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboCadJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCadJogoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Descrição do Game:");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextPaneDescJogo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextPaneDescJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane8.setViewportView(jTextPaneDescJogo);

        jButtonCadJogos.setBackground(new java.awt.Color(64, 77, 137));
        jButtonCadJogos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCadJogos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadJogos.setText("Cadastrar");
        jButtonCadJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadJogosActionPerformed(evt);
            }
        });

        jButton1.setText("Selecionar imagem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPrecoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCadJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCadJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CampoNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(364, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboCadJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoPrecoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonCadJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(CampoNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );

        setBounds(280, 25, 800, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeJogoActionPerformed

    private void jComboCadJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCadJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCadJogoActionPerformed

    private void jButtonCadJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadJogosActionPerformed
        games jogo = new games ();
        String ver ;
        boolean ver1 = false;

        GamesDAO gameDao = new GamesDAO ();

        ver = this.CampoNomeJogo.getText();
        ver = ver.replace(" ", "");
        if (ver.isEmpty()){
            ver1 = true;
        }
        if (ver1 == false){
            ver = this.CampoPrecoJogo.getText();
            ver = ver.replace(" ", "");
            if (ver.isEmpty()){
                ver1 = true;
            }
            if (ver1 == false){
                ver = this.jTextPaneDescJogo.getText();
                ver = ver.replace(" ", "");
                if (ver.isEmpty()){
                    ver1 = true;
                }
                if (ver1 == false){
                    if (CadAtu.equals("Cadastrar")){

                        jogo.setNome(this.CampoNomeJogo.getText());
                        jogo.setValor(this.CampoPrecoJogo.getText());
                        jogo.setDescricao(this.jTextPaneDescJogo.getText());
                        jogo.setSituacao("I");
                        ComboItem c = (ComboItem) this.jComboCadJogo.getSelectedItem();
                        jogo.setId_genero(c.getCodigo());
                        jogo.setImagem(ManipularImagem.getImgBytes(imagem));

                        if (gameDao.salvarImagem(jogo)){
                            addEstoque(CampoNomeJogo.getText());
                            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");
                            
                            
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Problemas ao salvar registro!");
                        }
                    } else {
                        jogo.setId_game(id);
                        jogo.setNome(this.CampoNomeJogo.getText());
                        jogo.setValor(this.CampoPrecoJogo.getText());
                        jogo.setDescricao(this.jTextPaneDescJogo.getText());
                        ComboItem c = (ComboItem) this.jComboCadJogo.getSelectedItem();
                        jogo.setId_genero(c.getCodigo());

                        if (gameDao.atualizarCadastro(jogo)){
                            JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso!");
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Problemas ao salvar registro!");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Preencha a descrição do jogo!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Preencha o valor do jogo!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha o nome do jogo!");
        }


    }//GEN-LAST:event_jButtonCadJogosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 250, 308);

                lblImagem.setIcon(new ImageIcon(imagem));

            } catch (Exception ex) {
               // System.out.println(ex.printStackTrace().toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoNomeJogo;
    private javax.swing.JFormattedTextField CampoPrecoJogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadJogos;
    private javax.swing.JComboBox<String> jComboCadJogo;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPaneDescJogo;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
